import React from 'react';
import {Link} from "react-router-dom";
import Footer from './common/Footer';



function FontIcons() {
    return (
        <div id="top">
        


{/* <!-- Top Background Image Wrapper --> */}
<div className="bgded overlay"> 

{/* <div className="bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');"> */} 
  
  <div className="wrapper row1">
    <header id="header" className="hoc clear"> 
        
      <div id="logo" className="fl_left">
        <h1><Link to="/">Yeinydd</Link></h1>
      </div>
      
      <nav id="mainav" className="fl_right">
        <ul className="clear">
          <li><Link to="/">Home</Link></li>
          <li className="active"><a className="drop" href="#">Pages</a>
            <ul>
              <li><Link to="/gallery">Gallery</Link></li>
              <li><Link to="/fullwidth">Full Width</Link></li>
              <li><Link to="/sidebarleft">Sidebarleft</Link></li>
              <li><Link to="/sidebarright">Sidebarright</Link></li>
              <li><Link to="/basicgrid">Basicgrid</Link></li>
              <li className="active"><Link to="/fonticons">Font-Icons</Link>
</li>
            </ul>
          </li>
          <li><a className="drop" href="#">Dropdown</a>
            <ul>
              <li><a href="#">Level 2</a></li>
              <li><a className="drop" href="#">Level 2 + Drop</a>
                <ul>
                  <li><a href="#">Level 3</a></li>
                  <li><a href="#">Level 3</a></li>
                  <li><a href="#">Level 3</a></li>
                </ul>
              </li>
              <li><a href="#">Level 2</a></li>
            </ul>
          </li>
          {/* <li><a href="#">Link Text</a></li>
          <li><a href="#">Link Text</a></li>
          <li><a href="#">Link Text</a></li>
          <li><a href="#">Long Link Text</a></li> */}
        </ul>
      </nav>
      
    </header>
  </div>
  
  
  
  <div id="breadcrumb" className="hoc clear"> 
    
    <h6 className="heading">Font Icons</h6>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Lorem</a></li>
      <li><a href="#">Ipsum</a></li>
      <li><a href="#">Dolor</a></li>
    </ul>
    
  </div>
  
</div>
{/* <!-- End Top Background Image Wrapper --> */}



<div className="wrapper row3">
  <main className="hoc container clear"> 
    {/* <!-- main body --> */}
    
    <div className="content"> 
      
      <div className="clear btmspace-50">
        <h2>Font Awesome 5.0.9</h2>
        <p className="clear">For further information, including integration and use, take a look at the <a target="_blank" rel="nofollow noopener" href="https://fontawesome.com/">Font Awesome Homepage <i className="fas fa-arrow-right fa-lg"></i></a></p>
      </div>
      
      
      
      <div className="clear btmspace-50">
        <h2>Solid Icons (fas)</h2>
        <div className="one_quarter first">
          <ul className="nospace">
            <li><i className="fa-address-book fa-fw fas"></i> fas fa-address-book</li>
            <li><i className="fa-address-card fa-fw fas"></i> fas fa-address-card</li>
            <li><i className="fa-adjust fa-fw fas"></i> fas fa-adjust</li>
            <li><i className="fa-align-center fa-fw fas"></i> fas fa-align-center</li>
            <li><i className="fa-align-justify fa-fw fas"></i> fas fa-align-justify</li>
            <li><i className="fa-align-left fa-fw fas"></i> fas fa-align-left</li>
            <li><i className="fa-align-right fa-fw fas"></i> fas fa-align-right</li>
            <li><i className="fa-allergies fa-fw fas"></i> fas fa-allergies</li>
            <li><i className="fa-ambulance fa-fw fas"></i> fas fa-ambulance</li>
            <li><i className="fa-american-sign-language-interpreting fa-fw fas"></i> fas fa-american-sign-language-interpreting</li>
            <li><i className="fa-anchor fa-fw fas"></i> fas fa-anchor</li>
            <li><i className="fa-angle-double-down fa-fw fas"></i> fas fa-angle-double-down</li>
            <li><i className="fa-angle-double-left fa-fw fas"></i> fas fa-angle-double-left</li>
            <li><i className="fa-angle-double-right fa-fw fas"></i> fas fa-angle-double-right</li>
            <li><i className="fa-angle-double-up fa-fw fas"></i> fas fa-angle-double-up</li>
            <li><i className="fa-angle-down fa-fw fas"></i> fas fa-angle-down</li>
            <li><i className="fa-angle-left fa-fw fas"></i> fas fa-angle-left</li>
            <li><i className="fa-angle-right fa-fw fas"></i> fas fa-angle-right</li>
            <li><i className="fa-angle-up fa-fw fas"></i> fas fa-angle-up</li>
            <li><i className="fa-archive fa-fw fas"></i> fas fa-archive</li>
            <li><i className="fa-arrow-alt-circle-down fa-fw fas"></i> fas fa-arrow-alt-circle-down</li>
            <li><i className="fa-arrow-alt-circle-left fa-fw fas"></i> fas fa-arrow-alt-circle-left</li>
            <li><i className="fa-arrow-alt-circle-right fa-fw fas"></i> fas fa-arrow-alt-circle-right</li>
            <li><i className="fa-arrow-alt-circle-up fa-fw fas"></i> fas fa-arrow-alt-circle-up</li>
            <li><i className="fa-arrow-circle-down fa-fw fas"></i> fas fa-arrow-circle-down</li>
            <li><i className="fa-arrow-circle-left fa-fw fas"></i> fas fa-arrow-circle-left</li>
            <li><i className="fa-arrow-circle-right fa-fw fas"></i> fas fa-arrow-circle-right</li>
            <li><i className="fa-arrow-circle-up fa-fw fas"></i> fas fa-arrow-circle-up</li>
            <li><i className="fa-arrow-down fa-fw fas"></i> fas fa-arrow-down</li>
            <li><i className="fa-arrow-left fa-fw fas"></i> fas fa-arrow-left</li>
            <li><i className="fa-arrow-right fa-fw fas"></i> fas fa-arrow-right</li>
            <li><i className="fa-arrow-up fa-fw fas"></i> fas fa-arrow-up</li>
            <li><i className="fa-arrows-alt fa-fw fas"></i> fas fa-arrows-alt</li>
            <li><i className="fa-arrows-alt-h fa-fw fas"></i> fas fa-arrows-alt-h</li>
            <li><i className="fa-arrows-alt-v fa-fw fas"></i> fas fa-arrows-alt-v</li>
            <li><i className="fa-assistive-listening-systems fa-fw fas"></i> fas fa-assistive-listening-systems</li>
            <li><i className="fa-asterisk fa-fw fas"></i> fas fa-asterisk</li>
            <li><i className="fa-at fa-fw fas"></i> fas fa-at</li>
            <li><i className="fa-audio-description fa-fw fas"></i> fas fa-audio-description</li>
            <li><i className="fa-backward fa-fw fas"></i> fas fa-backward</li>
            <li><i className="fa-balance-scale fa-fw fas"></i> fas fa-balance-scale</li>
            <li><i className="fa-ban fa-fw fas"></i> fas fa-ban</li>
            <li><i className="fa-band-aid fa-fw fas"></i> fas fa-band-aid</li>
            <li><i className="fa-barcode fa-fw fas"></i> fas fa-barcode</li>
            <li><i className="fa-bars fa-fw fas"></i> fas fa-bars</li>
            <li><i className="fa-baseball-ball fa-fw fas"></i> fas fa-baseball-ball</li>
            <li><i className="fa-basketball-ball fa-fw fas"></i> fas fa-basketball-ball</li>
            <li><i className="fa-bath fa-fw fas"></i> fas fa-bath</li>
            <li><i className="fa-battery-empty fa-fw fas"></i> fas fa-battery-empty</li>
            <li><i className="fa-battery-full fa-fw fas"></i> fas fa-battery-full</li>
            <li><i className="fa-battery-half fa-fw fas"></i> fas fa-battery-half</li>
            <li><i className="fa-battery-quarter fa-fw fas"></i> fas fa-battery-quarter</li>
            <li><i className="fa-battery-three-quarters fa-fw fas"></i> fas fa-battery-three-quarters</li>
            <li><i className="fa-bed fa-fw fas"></i> fas fa-bed</li>
            <li><i className="fa-beer fa-fw fas"></i> fas fa-beer</li>
            <li><i className="fa-bell fa-fw fas"></i> fas fa-bell</li>
            <li><i className="fa-bell-slash fa-fw fas"></i> fas fa-bell-slash</li>
            <li><i className="fa-bicycle fa-fw fas"></i> fas fa-bicycle</li>
            <li><i className="fa-binoculars fa-fw fas"></i> fas fa-binoculars</li>
            <li><i className="fa-birthday-cake fa-fw fas"></i> fas fa-birthday-cake</li>
            <li><i className="fa-blind fa-fw fas"></i> fas fa-blind</li>
            <li><i className="fa-bold fa-fw fas"></i> fas fa-bold</li>
            <li><i className="fa-bolt fa-fw fas"></i> fas fa-bolt</li>
            <li><i className="fa-bomb fa-fw fas"></i> fas fa-bomb</li>
            <li><i className="fa-book fa-fw fas"></i> fas fa-book</li>
            <li><i className="fa-bookmark fa-fw fas"></i> fas fa-bookmark</li>
            <li><i className="fa-bowling-ball fa-fw fas"></i> fas fa-bowling-ball</li>
            <li><i className="fa-box fa-fw fas"></i> fas fa-box</li>
            <li><i className="fa-box-open fa-fw fas"></i> fas fa-box-open</li>
            <li><i className="fa-boxes fa-fw fas"></i> fas fa-boxes</li>
            <li><i className="fa-braille fa-fw fas"></i> fas fa-braille</li>
            <li><i className="fa-briefcase fa-fw fas"></i> fas fa-briefcase</li>
            <li><i className="fa-briefcase-medical fa-fw fas"></i> fas fa-briefcase-medical</li>
            <li><i className="fa-bug fa-fw fas"></i> fas fa-bug</li>
            <li><i className="fa-building fa-fw fas"></i> fas fa-building</li>
            <li><i className="fa-bullhorn fa-fw fas"></i> fas fa-bullhorn</li>
            <li><i className="fa-bullseye fa-fw fas"></i> fas fa-bullseye</li>
            <li><i className="fa-burn fa-fw fas"></i> fas fa-burn</li>
            <li><i className="fa-bus fa-fw fas"></i> fas fa-bus</li>
            <li><i className="fa-calculator fa-fw fas"></i> fas fa-calculator</li>
            <li><i className="fa-calendar fa-fw fas"></i> fas fa-calendar</li>
            <li><i className="fa-calendar-alt fa-fw fas"></i> fas fa-calendar-alt</li>
            <li><i className="fa-calendar-check fa-fw fas"></i> fas fa-calendar-check</li>
            <li><i className="fa-calendar-minus fa-fw fas"></i> fas fa-calendar-minus</li>
            <li><i className="fa-calendar-plus fa-fw fas"></i> fas fa-calendar-plus</li>
            <li><i className="fa-calendar-times fa-fw fas"></i> fas fa-calendar-times</li>
            <li><i className="fa-camera fa-fw fas"></i> fas fa-camera</li>
            <li><i className="fa-camera-retro fa-fw fas"></i> fas fa-camera-retro</li>
            <li><i className="fa-capsules fa-fw fas"></i> fas fa-capsules</li>
            <li><i className="fa-car fa-fw fas"></i> fas fa-car</li>
            <li><i className="fa-caret-down fa-fw fas"></i> fas fa-caret-down</li>
            <li><i className="fa-caret-left fa-fw fas"></i> fas fa-caret-left</li>
            <li><i className="fa-caret-right fa-fw fas"></i> fas fa-caret-right</li>
            <li><i className="fa-caret-square-down fa-fw fas"></i> fas fa-caret-square-down</li>
            <li><i className="fa-caret-square-left fa-fw fas"></i> fas fa-caret-square-left</li>
            <li><i className="fa-caret-square-right fa-fw fas"></i> fas fa-caret-square-right</li>
            <li><i className="fa-caret-square-up fa-fw fas"></i> fas fa-caret-square-up</li>
            <li><i className="fa-caret-up fa-fw fas"></i> fas fa-caret-up</li>
            <li><i className="fa-cart-arrow-down fa-fw fas"></i> fas fa-cart-arrow-down</li>
            <li><i className="fa-cart-plus fa-fw fas"></i> fas fa-cart-plus</li>
            <li><i className="fa-certificate fa-fw fas"></i> fas fa-certificate</li>
            <li><i className="fa-chart-area fa-fw fas"></i> fas fa-chart-area</li>
            <li><i className="fa-chart-bar fa-fw fas"></i> fas fa-chart-bar</li>
            <li><i className="fa-chart-line fa-fw fas"></i> fas fa-chart-line</li>
            <li><i className="fa-chart-pie fa-fw fas"></i> fas fa-chart-pie</li>
            <li><i className="fa-check fa-fw fas"></i> fas fa-check</li>
            <li><i className="fa-check-circle fa-fw fas"></i> fas fa-check-circle</li>
            <li><i className="fa-check-square fa-fw fas"></i> fas fa-check-square</li>
            <li><i className="fa-chess fa-fw fas"></i> fas fa-chess</li>
            <li><i className="fa-chess-bishop fa-fw fas"></i> fas fa-chess-bishop</li>
            <li><i className="fa-chess-board fa-fw fas"></i> fas fa-chess-board</li>
            <li><i className="fa-chess-king fa-fw fas"></i> fas fa-chess-king</li>
            <li><i className="fa-chess-knight fa-fw fas"></i> fas fa-chess-knight</li>
            <li><i className="fa-chess-pawn fa-fw fas"></i> fas fa-chess-pawn</li>
            <li><i className="fa-chess-queen fa-fw fas"></i> fas fa-chess-queen</li>
            <li><i className="fa-chess-rook fa-fw fas"></i> fas fa-chess-rook</li>
            <li><i className="fa-chevron-circle-down fa-fw fas"></i> fas fa-chevron-circle-down</li>
            <li><i className="fa-chevron-circle-left fa-fw fas"></i> fas fa-chevron-circle-left</li>
            <li><i className="fa-chevron-circle-right fa-fw fas"></i> fas fa-chevron-circle-right</li>
            <li><i className="fa-chevron-circle-up fa-fw fas"></i> fas fa-chevron-circle-up</li>
            <li><i className="fa-chevron-down fa-fw fas"></i> fas fa-chevron-down</li>
            <li><i className="fa-chevron-left fa-fw fas"></i> fas fa-chevron-left</li>
            <li><i className="fa-chevron-right fa-fw fas"></i> fas fa-chevron-right</li>
            <li><i className="fa-chevron-up fa-fw fas"></i> fas fa-chevron-up</li>
            <li><i className="fa-child fa-fw fas"></i> fas fa-child</li>
            <li><i className="fa-circle fa-fw fas"></i> fas fa-circle</li>
            <li><i className="fa-circle-notch fa-fw fas"></i> fas fa-circle-notch</li>
            <li><i className="fa-clipboard fa-fw fas"></i> fas fa-clipboard</li>
            <li><i className="fa-clipboard-check fa-fw fas"></i> fas fa-clipboard-check</li>
            <li><i className="fa-clipboard-list fa-fw fas"></i> fas fa-clipboard-list</li>
            <li><i className="fa-clock fa-fw fas"></i> fas fa-clock</li>
            <li><i className="fa-clone fa-fw fas"></i> fas fa-clone</li>
            <li><i className="fa-closed-captioning fa-fw fas"></i> fas fa-closed-captioning</li>
            <li><i className="fa-cloud fa-fw fas"></i> fas fa-cloud</li>
            <li><i className="fa-cloud-download-alt fa-fw fas"></i> fas fa-cloud-download-alt</li>
            <li><i className="fa-cloud-upload-alt fa-fw fas"></i> fas fa-cloud-upload-alt</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-code fa-fw fas"></i> fas fa-code</li>
            <li><i className="fa-code-branch fa-fw fas"></i> fas fa-code-branch</li>
            <li><i className="fa-coffee fa-fw fas"></i> fas fa-coffee</li>
            <li><i className="fa-cog fa-fw fas"></i> fas fa-cog</li>
            <li><i className="fa-cogs fa-fw fas"></i> fas fa-cogs</li>
            <li><i className="fa-columns fa-fw fas"></i> fas fa-columns</li>
            <li><i className="fa-comment fa-fw fas"></i> fas fa-comment</li>
            <li><i className="fa-comment-alt fa-fw fas"></i> fas fa-comment-alt</li>
            <li><i className="fa-comment-dots fa-fw fas"></i> fas fa-comment-dots</li>
            <li><i className="fa-comment-slash fa-fw fas"></i> fas fa-comment-slash</li>
            <li><i className="fa-comments fa-fw fas"></i> fas fa-comments</li>
            <li><i className="fa-compass fa-fw fas"></i> fas fa-compass</li>
            <li><i className="fa-compress fa-fw fas"></i> fas fa-compress</li>
            <li><i className="fa-copy fa-fw fas"></i> fas fa-copy</li>
            <li><i className="fa-copyright fa-fw fas"></i> fas fa-copyright</li>
            <li><i className="fa-couch fa-fw fas"></i> fas fa-couch</li>
            <li><i className="fa-credit-card fa-fw fas"></i> fas fa-credit-card</li>
            <li><i className="fa-crop fa-fw fas"></i> fas fa-crop</li>
            <li><i className="fa-crosshairs fa-fw fas"></i> fas fa-crosshairs</li>
            <li><i className="fa-cube fa-fw fas"></i> fas fa-cube</li>
            <li><i className="fa-cubes fa-fw fas"></i> fas fa-cubes</li>
            <li><i className="fa-cut fa-fw fas"></i> fas fa-cut</li>
            <li><i className="fa-database fa-fw fas"></i> fas fa-database</li>
            <li><i className="fa-deaf fa-fw fas"></i> fas fa-deaf</li>
            <li><i className="fa-desktop fa-fw fas"></i> fas fa-desktop</li>
            <li><i className="fa-diagnoses fa-fw fas"></i> fas fa-diagnoses</li>
            <li><i className="fa-dna fa-fw fas"></i> fas fa-dna</li>
            <li><i className="fa-dollar-sign fa-fw fas"></i> fas fa-dollar-sign</li>
            <li><i className="fa-dolly fa-fw fas"></i> fas fa-dolly</li>
            <li><i className="fa-dolly-flatbed fa-fw fas"></i> fas fa-dolly-flatbed</li>
            <li><i className="fa-donate fa-fw fas"></i> fas fa-donate</li>
            <li><i className="fa-dot-circle fa-fw fas"></i> fas fa-dot-circle</li>
            <li><i className="fa-dove fa-fw fas"></i> fas fa-dove</li>
            <li><i className="fa-download fa-fw fas"></i> fas fa-download</li>
            <li><i className="fa-edit fa-fw fas"></i> fas fa-edit</li>
            <li><i className="fa-eject fa-fw fas"></i> fas fa-eject</li>
            <li><i className="fa-ellipsis-h fa-fw fas"></i> fas fa-ellipsis-h</li>
            <li><i className="fa-ellipsis-v fa-fw fas"></i> fas fa-ellipsis-v</li>
            <li><i className="fa-envelope fa-fw fas"></i> fas fa-envelope</li>
            <li><i className="fa-envelope-open fa-fw fas"></i> fas fa-envelope-open</li>
            <li><i className="fa-envelope-square fa-fw fas"></i> fas fa-envelope-square</li>
            <li><i className="fa-eraser fa-fw fas"></i> fas fa-eraser</li>
            <li><i className="fa-euro-sign fa-fw fas"></i> fas fa-euro-sign</li>
            <li><i className="fa-exchange-alt fa-fw fas"></i> fas fa-exchange-alt</li>
            <li><i className="fa-exclamation fa-fw fas"></i> fas fa-exclamation</li>
            <li><i className="fa-exclamation-circle fa-fw fas"></i> fas fa-exclamation-circle</li>
            <li><i className="fa-exclamation-triangle fa-fw fas"></i> fas fa-exclamation-triangle</li>
            <li><i className="fa-expand fa-fw fas"></i> fas fa-expand</li>
            <li><i className="fa-expand-arrows-alt fa-fw fas"></i> fas fa-expand-arrows-alt</li>
            <li><i className="fa-external-link-alt fa-fw fas"></i> fas fa-external-link-alt</li>
            <li><i className="fa-external-link-square-alt fa-fw fas"></i> fas fa-external-link-square-alt</li>
            <li><i className="fa-eye fa-fw fas"></i> fas fa-eye</li>
            <li><i className="fa-eye-dropper fa-fw fas"></i> fas fa-eye-dropper</li>
            <li><i className="fa-eye-slash fa-fw fas"></i> fas fa-eye-slash</li>
            <li><i className="fa-fast-backward fa-fw fas"></i> fas fa-fast-backward</li>
            <li><i className="fa-fast-forward fa-fw fas"></i> fas fa-fast-forward</li>
            <li><i className="fa-fax fa-fw fas"></i> fas fa-fax</li>
            <li><i className="fa-female fa-fw fas"></i> fas fa-female</li>
            <li><i className="fa-fighter-jet fa-fw fas"></i> fas fa-fighter-jet</li>
            <li><i className="fa-file fa-fw fas"></i> fas fa-file</li>
            <li><i className="fa-file-alt fa-fw fas"></i> fas fa-file-alt</li>
            <li><i className="fa-file-archive fa-fw fas"></i> fas fa-file-archive</li>
            <li><i className="fa-file-audio fa-fw fas"></i> fas fa-file-audio</li>
            <li><i className="fa-file-code fa-fw fas"></i> fas fa-file-code</li>
            <li><i className="fa-file-excel fa-fw fas"></i> fas fa-file-excel</li>
            <li><i className="fa-file-image fa-fw fas"></i> fas fa-file-image</li>
            <li><i className="fa-file-medical fa-fw fas"></i> fas fa-file-medical</li>
            <li><i className="fa-file-medical-alt fa-fw fas"></i> fas fa-file-medical-alt</li>
            <li><i className="fa-file-pdf fa-fw fas"></i> fas fa-file-pdf</li>
            <li><i className="fa-file-powerpoint fa-fw fas"></i> fas fa-file-powerpoint</li>
            <li><i className="fa-file-video fa-fw fas"></i> fas fa-file-video</li>
            <li><i className="fa-file-word fa-fw fas"></i> fas fa-file-word</li>
            <li><i className="fa-film fa-fw fas"></i> fas fa-film</li>
            <li><i className="fa-filter fa-fw fas"></i> fas fa-filter</li>
            <li><i className="fa-fire fa-fw fas"></i> fas fa-fire</li>
            <li><i className="fa-fire-extinguisher fa-fw fas"></i> fas fa-fire-extinguisher</li>
            <li><i className="fa-first-aid fa-fw fas"></i> fas fa-first-aid</li>
            <li><i className="fa-flag fa-fw fas"></i> fas fa-flag</li>
            <li><i className="fa-flag-checkered fa-fw fas"></i> fas fa-flag-checkered</li>
            <li><i className="fa-flask fa-fw fas"></i> fas fa-flask</li>
            <li><i className="fa-folder fa-fw fas"></i> fas fa-folder</li>
            <li><i className="fa-folder-open fa-fw fas"></i> fas fa-folder-open</li>
            <li><i className="fa-font fa-fw fas"></i> fas fa-font</li>
            <li><i className="fa-football-ball fa-fw fas"></i> fas fa-football-ball</li>
            <li><i className="fa-forward fa-fw fas"></i> fas fa-forward</li>
            <li><i className="fa-frown fa-fw fas"></i> fas fa-frown</li>
            <li><i className="fa-futbol fa-fw fas"></i> fas fa-futbol</li>
            <li><i className="fa-gamepad fa-fw fas"></i> fas fa-gamepad</li>
            <li><i className="fa-gavel fa-fw fas"></i> fas fa-gavel</li>
            <li><i className="fa-gem fa-fw fas"></i> fas fa-gem</li>
            <li><i className="fa-genderless fa-fw fas"></i> fas fa-genderless</li>
            <li><i className="fa-gift fa-fw fas"></i> fas fa-gift</li>
            <li><i className="fa-glass-martini fa-fw fas"></i> fas fa-glass-martini</li>
            <li><i className="fa-globe fa-fw fas"></i> fas fa-globe</li>
            <li><i className="fa-golf-ball fa-fw fas"></i> fas fa-golf-ball</li>
            <li><i className="fa-graduation-cap fa-fw fas"></i> fas fa-graduation-cap</li>
            <li><i className="fa-h-square fa-fw fas"></i> fas fa-h-square</li>
            <li><i className="fa-hand-holding fa-fw fas"></i> fas fa-hand-holding</li>
            <li><i className="fa-hand-holding-heart fa-fw fas"></i> fas fa-hand-holding-heart</li>
            <li><i className="fa-hand-holding-usd fa-fw fas"></i> fas fa-hand-holding-usd</li>
            <li><i className="fa-hand-lizard fa-fw fas"></i> fas fa-hand-lizard</li>
            <li><i className="fa-hand-paper fa-fw fas"></i> fas fa-hand-paper</li>
            <li><i className="fa-hand-peace fa-fw fas"></i> fas fa-hand-peace</li>
            <li><i className="fa-hand-point-down fa-fw fas"></i> fas fa-hand-point-down</li>
            <li><i className="fa-hand-point-left fa-fw fas"></i> fas fa-hand-point-left</li>
            <li><i className="fa-hand-point-right fa-fw fas"></i> fas fa-hand-point-right</li>
            <li><i className="fa-hand-point-up fa-fw fas"></i> fas fa-hand-point-up</li>
            <li><i className="fa-hand-pointer fa-fw fas"></i> fas fa-hand-pointer</li>
            <li><i className="fa-hand-rock fa-fw fas"></i> fas fa-hand-rock</li>
            <li><i className="fa-hand-scissors fa-fw fas"></i> fas fa-hand-scissors</li>
            <li><i className="fa-hand-spock fa-fw fas"></i> fas fa-hand-spock</li>
            <li><i className="fa-hands fa-fw fas"></i> fas fa-hands</li>
            <li><i className="fa-hands-helping fa-fw fas"></i> fas fa-hands-helping</li>
            <li><i className="fa-handshake fa-fw fas"></i> fas fa-handshake</li>
            <li><i className="fa-hashtag fa-fw fas"></i> fas fa-hashtag</li>
            <li><i className="fa-hdd fa-fw fas"></i> fas fa-hdd</li>
            <li><i className="fa-heading fa-fw fas"></i> fas fa-heading</li>
            <li><i className="fa-headphones fa-fw fas"></i> fas fa-headphones</li>
            <li><i className="fa-heart fa-fw fas"></i> fas fa-heart</li>
            <li><i className="fa-heartbeat fa-fw fas"></i> fas fa-heartbeat</li>
            <li><i className="fa-history fa-fw fas"></i> fas fa-history</li>
            <li><i className="fa-hockey-puck fa-fw fas"></i> fas fa-hockey-puck</li>
            <li><i className="fa-home fa-fw fas"></i> fas fa-home</li>
            <li><i className="fa-hospital fa-fw fas"></i> fas fa-hospital</li>
            <li><i className="fa-hospital-alt fa-fw fas"></i> fas fa-hospital-alt</li>
            <li><i className="fa-hospital-symbol fa-fw fas"></i> fas fa-hospital-symbol</li>
            <li><i className="fa-hourglass fa-fw fas"></i> fas fa-hourglass</li>
            <li><i className="fa-hourglass-end fa-fw fas"></i> fas fa-hourglass-end</li>
            <li><i className="fa-hourglass-half fa-fw fas"></i> fas fa-hourglass-half</li>
            <li><i className="fa-hourglass-start fa-fw fas"></i> fas fa-hourglass-start</li>
            <li><i className="fa-i-cursor fa-fw fas"></i> fas fa-i-cursor</li>
            <li><i className="fa-id-badge fa-fw fas"></i> fas fa-id-badge</li>
            <li><i className="fa-id-card fa-fw fas"></i> fas fa-id-card</li>
            <li><i className="fa-id-card-alt fa-fw fas"></i> fas fa-id-card-alt</li>
            <li><i className="fa-image fa-fw fas"></i> fas fa-image</li>
            <li><i className="fa-images fa-fw fas"></i> fas fa-images</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-inbox fa-fw fas"></i> fas fa-inbox</li>
            <li><i className="fa-indent fa-fw fas"></i> fas fa-indent</li>
            <li><i className="fa-industry fa-fw fas"></i> fas fa-industry</li>
            <li><i className="fa-info fa-fw fas"></i> fas fa-info</li>
            <li><i className="fa-info-circle fa-fw fas"></i> fas fa-info-circle</li>
            <li><i className="fa-italic fa-fw fas"></i> fas fa-italic</li>
            <li><i className="fa-key fa-fw fas"></i> fas fa-key</li>
            <li><i className="fa-keyboard fa-fw fas"></i> fas fa-keyboard</li>
            <li><i className="fa-language fa-fw fas"></i> fas fa-language</li>
            <li><i className="fa-laptop fa-fw fas"></i> fas fa-laptop</li>
            <li><i className="fa-leaf fa-fw fas"></i> fas fa-leaf</li>
            <li><i className="fa-lemon fa-fw fas"></i> fas fa-lemon</li>
            <li><i className="fa-level-down-alt fa-fw fas"></i> fas fa-level-down-alt</li>
            <li><i className="fa-level-up-alt fa-fw fas"></i> fas fa-level-up-alt</li>
            <li><i className="fa-life-ring fa-fw fas"></i> fas fa-life-ring</li>
            <li><i className="fa-lightbulb fa-fw fas"></i> fas fa-lightbulb</li>
            <li><i className="fa-link fa-fw fas"></i> fas fa-link</li>
            <li><i className="fa-lira-sign fa-fw fas"></i> fas fa-lira-sign</li>
            <li><i className="fa-list fa-fw fas"></i> fas fa-list</li>
            <li><i className="fa-list-alt fa-fw fas"></i> fas fa-list-alt</li>
            <li><i className="fa-list-ol fa-fw fas"></i> fas fa-list-ol</li>
            <li><i className="fa-list-ul fa-fw fas"></i> fas fa-list-ul</li>
            <li><i className="fa-location-arrow fa-fw fas"></i> fas fa-location-arrow</li>
            <li><i className="fa-lock fa-fw fas"></i> fas fa-lock</li>
            <li><i className="fa-lock-open fa-fw fas"></i> fas fa-lock-open</li>
            <li><i className="fa-long-arrow-alt-down fa-fw fas"></i> fas fa-long-arrow-alt-down</li>
            <li><i className="fa-long-arrow-alt-left fa-fw fas"></i> fas fa-long-arrow-alt-left</li>
            <li><i className="fa-long-arrow-alt-right fa-fw fas"></i> fas fa-long-arrow-alt-right</li>
            <li><i className="fa-long-arrow-alt-up fa-fw fas"></i> fas fa-long-arrow-alt-up</li>
            <li><i className="fa-low-vision fa-fw fas"></i> fas fa-low-vision</li>
            <li><i className="fa-magic fa-fw fas"></i> fas fa-magic</li>
            <li><i className="fa-magnet fa-fw fas"></i> fas fa-magnet</li>
            <li><i className="fa-male fa-fw fas"></i> fas fa-male</li>
            <li><i className="fa-map fa-fw fas"></i> fas fa-map</li>
            <li><i className="fa-map-marker fa-fw fas"></i> fas fa-map-marker</li>
            <li><i className="fa-map-marker-alt fa-fw fas"></i> fas fa-map-marker-alt</li>
            <li><i className="fa-map-pin fa-fw fas"></i> fas fa-map-pin</li>
            <li><i className="fa-map-signs fa-fw fas"></i> fas fa-map-signs</li>
            <li><i className="fa-mars fa-fw fas"></i> fas fa-mars</li>
            <li><i className="fa-mars-double fa-fw fas"></i> fas fa-mars-double</li>
            <li><i className="fa-mars-stroke fa-fw fas"></i> fas fa-mars-stroke</li>
            <li><i className="fa-mars-stroke-h fa-fw fas"></i> fas fa-mars-stroke-h</li>
            <li><i className="fa-mars-stroke-v fa-fw fas"></i> fas fa-mars-stroke-v</li>
            <li><i className="fa-medkit fa-fw fas"></i> fas fa-medkit</li>
            <li><i className="fa-meh fa-fw fas"></i> fas fa-meh</li>
            <li><i className="fa-mercury fa-fw fas"></i> fas fa-mercury</li>
            <li><i className="fa-microchip fa-fw fas"></i> fas fa-microchip</li>
            <li><i className="fa-microphone fa-fw fas"></i> fas fa-microphone</li>
            <li><i className="fa-microphone-slash fa-fw fas"></i> fas fa-microphone-slash</li>
            <li><i className="fa-minus fa-fw fas"></i> fas fa-minus</li>
            <li><i className="fa-minus-circle fa-fw fas"></i> fas fa-minus-circle</li>
            <li><i className="fa-minus-square fa-fw fas"></i> fas fa-minus-square</li>
            <li><i className="fa-mobile fa-fw fas"></i> fas fa-mobile</li>
            <li><i className="fa-mobile-alt fa-fw fas"></i> fas fa-mobile-alt</li>
            <li><i className="fa-money-bill-alt fa-fw fas"></i> fas fa-money-bill-alt</li>
            <li><i className="fa-moon fa-fw fas"></i> fas fa-moon</li>
            <li><i className="fa-motorcycle fa-fw fas"></i> fas fa-motorcycle</li>
            <li><i className="fa-mouse-pointer fa-fw fas"></i> fas fa-mouse-pointer</li>
            <li><i className="fa-music fa-fw fas"></i> fas fa-music</li>
            <li><i className="fa-neuter fa-fw fas"></i> fas fa-neuter</li>
            <li><i className="fa-newspaper fa-fw fas"></i> fas fa-newspaper</li>
            <li><i className="fa-notes-medical fa-fw fas"></i> fas fa-notes-medical</li>
            <li><i className="fa-object-group fa-fw fas"></i> fas fa-object-group</li>
            <li><i className="fa-object-ungroup fa-fw fas"></i> fas fa-object-ungroup</li>
            <li><i className="fa-outdent fa-fw fas"></i> fas fa-outdent</li>
            <li><i className="fa-paint-brush fa-fw fas"></i> fas fa-paint-brush</li>
            <li><i className="fa-pallet fa-fw fas"></i> fas fa-pallet</li>
            <li><i className="fa-paper-plane fa-fw fas"></i> fas fa-paper-plane</li>
            <li><i className="fa-paperclip fa-fw fas"></i> fas fa-paperclip</li>
            <li><i className="fa-parachute-box fa-fw fas"></i> fas fa-parachute-box</li>
            <li><i className="fa-paragraph fa-fw fas"></i> fas fa-paragraph</li>
            <li><i className="fa-paste fa-fw fas"></i> fas fa-paste</li>
            <li><i className="fa-pause fa-fw fas"></i> fas fa-pause</li>
            <li><i className="fa-pause-circle fa-fw fas"></i> fas fa-pause-circle</li>
            <li><i className="fa-paw fa-fw fas"></i> fas fa-paw</li>
            <li><i className="fa-pen-square fa-fw fas"></i> fas fa-pen-square</li>
            <li><i className="fa-pencil-alt fa-fw fas"></i> fas fa-pencil-alt</li>
            <li><i className="fa-people-carry fa-fw fas"></i> fas fa-people-carry</li>
            <li><i className="fa-percent fa-fw fas"></i> fas fa-percent</li>
            <li><i className="fa-phone fa-fw fas"></i> fas fa-phone</li>
            <li><i className="fa-phone-slash fa-fw fas"></i> fas fa-phone-slash</li>
            <li><i className="fa-phone-square fa-fw fas"></i> fas fa-phone-square</li>
            <li><i className="fa-phone-volume fa-fw fas"></i> fas fa-phone-volume</li>
            <li><i className="fa-piggy-bank fa-fw fas"></i> fas fa-piggy-bank</li>
            <li><i className="fa-pills fa-fw fas"></i> fas fa-pills</li>
            <li><i className="fa-plane fa-fw fas"></i> fas fa-plane</li>
            <li><i className="fa-play fa-fw fas"></i> fas fa-play</li>
            <li><i className="fa-play-circle fa-fw fas"></i> fas fa-play-circle</li>
            <li><i className="fa-plug fa-fw fas"></i> fas fa-plug</li>
            <li><i className="fa-plus fa-fw fas"></i> fas fa-plus</li>
            <li><i className="fa-plus-circle fa-fw fas"></i> fas fa-plus-circle</li>
            <li><i className="fa-plus-square fa-fw fas"></i> fas fa-plus-square</li>
            <li><i className="fa-podcast fa-fw fas"></i> fas fa-podcast</li>
            <li><i className="fa-poo fa-fw fas"></i> fas fa-poo</li>
            <li><i className="fa-pound-sign fa-fw fas"></i> fas fa-pound-sign</li>
            <li><i className="fa-power-off fa-fw fas"></i> fas fa-power-off</li>
            <li><i className="fa-prescription-bottle fa-fw fas"></i> fas fa-prescription-bottle</li>
            <li><i className="fa-prescription-bottle-alt fa-fw fas"></i> fas fa-prescription-bottle-alt</li>
            <li><i className="fa-print fa-fw fas"></i> fas fa-print</li>
            <li><i className="fa-procedures fa-fw fas"></i> fas fa-procedures</li>
            <li><i className="fa-puzzle-piece fa-fw fas"></i> fas fa-puzzle-piece</li>
            <li><i className="fa-qrcode fa-fw fas"></i> fas fa-qrcode</li>
            <li><i className="fa-question fa-fw fas"></i> fas fa-question</li>
            <li><i className="fa-question-circle fa-fw fas"></i> fas fa-question-circle</li>
            <li><i className="fa-quidditch fa-fw fas"></i> fas fa-quidditch</li>
            <li><i className="fa-quote-left fa-fw fas"></i> fas fa-quote-left</li>
            <li><i className="fa-quote-right fa-fw fas"></i> fas fa-quote-right</li>
            <li><i className="fa-random fa-fw fas"></i> fas fa-random</li>
            <li><i className="fa-recycle fa-fw fas"></i> fas fa-recycle</li>
            <li><i className="fa-redo fa-fw fas"></i> fas fa-redo</li>
            <li><i className="fa-redo-alt fa-fw fas"></i> fas fa-redo-alt</li>
            <li><i className="fa-registered fa-fw fas"></i> fas fa-registered</li>
            <li><i className="fa-reply fa-fw fas"></i> fas fa-reply</li>
            <li><i className="fa-reply-all fa-fw fas"></i> fas fa-reply-all</li>
            <li><i className="fa-retweet fa-fw fas"></i> fas fa-retweet</li>
            <li><i className="fa-ribbon fa-fw fas"></i> fas fa-ribbon</li>
            <li><i className="fa-road fa-fw fas"></i> fas fa-road</li>
            <li><i className="fa-rocket fa-fw fas"></i> fas fa-rocket</li>
            <li><i className="fa-rss fa-fw fas"></i> fas fa-rss</li>
            <li><i className="fa-rss-square fa-fw fas"></i> fas fa-rss-square</li>
            <li><i className="fa-ruble-sign fa-fw fas"></i> fas fa-ruble-sign</li>
            <li><i className="fa-rupee-sign fa-fw fas"></i> fas fa-rupee-sign</li>
            <li><i className="fa-save fa-fw fas"></i> fas fa-save</li>
            <li><i className="fa-search fa-fw fas"></i> fas fa-search</li>
            <li><i className="fa-search-minus fa-fw fas"></i> fas fa-search-minus</li>
            <li><i className="fa-search-plus fa-fw fas"></i> fas fa-search-plus</li>
            <li><i className="fa-seedling fa-fw fas"></i> fas fa-seedling</li>
            <li><i className="fa-server fa-fw fas"></i> fas fa-server</li>
            <li><i className="fa-share fa-fw fas"></i> fas fa-share</li>
            <li><i className="fa-share-alt fa-fw fas"></i> fas fa-share-alt</li>
            <li><i className="fa-share-alt-square fa-fw fas"></i> fas fa-share-alt-square</li>
            <li><i className="fa-share-square fa-fw fas"></i> fas fa-share-square</li>
            <li><i className="fa-shekel-sign fa-fw fas"></i> fas fa-shekel-sign</li>
            <li><i className="fa-shield-alt fa-fw fas"></i> fas fa-shield-alt</li>
            <li><i className="fa-ship fa-fw fas"></i> fas fa-ship</li>
            <li><i className="fa-shipping-fast fa-fw fas"></i> fas fa-shipping-fast</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-shopping-bag fa-fw fas"></i> fas fa-shopping-bag</li>
            <li><i className="fa-shopping-basket fa-fw fas"></i> fas fa-shopping-basket</li>
            <li><i className="fa-shopping-cart fa-fw fas"></i> fas fa-shopping-cart</li>
            <li><i className="fa-shower fa-fw fas"></i> fas fa-shower</li>
            <li><i className="fa-sign fa-fw fas"></i> fas fa-sign</li>
            <li><i className="fa-sign-in-alt fa-fw fas"></i> fas fa-sign-in-alt</li>
            <li><i className="fa-sign-language fa-fw fas"></i> fas fa-sign-language</li>
            <li><i className="fa-sign-out-alt fa-fw fas"></i> fas fa-sign-out-alt</li>
            <li><i className="fa-signal fa-fw fas"></i> fas fa-signal</li>
            <li><i className="fa-sitemap fa-fw fas"></i> fas fa-sitemap</li>
            <li><i className="fa-sliders-h fa-fw fas"></i> fas fa-sliders-h</li>
            <li><i className="fa-smile fa-fw fas"></i> fas fa-smile</li>
            <li><i className="fa-smoking fa-fw fas"></i> fas fa-smoking</li>
            <li><i className="fa-snowflake fa-fw fas"></i> fas fa-snowflake</li>
            <li><i className="fa-sort fa-fw fas"></i> fas fa-sort</li>
            <li><i className="fa-sort-alpha-down fa-fw fas"></i> fas fa-sort-alpha-down</li>
            <li><i className="fa-sort-alpha-up fa-fw fas"></i> fas fa-sort-alpha-up</li>
            <li><i className="fa-sort-amount-down fa-fw fas"></i> fas fa-sort-amount-down</li>
            <li><i className="fa-sort-amount-up fa-fw fas"></i> fas fa-sort-amount-up</li>
            <li><i className="fa-sort-down fa-fw fas"></i> fas fa-sort-down</li>
            <li><i className="fa-sort-numeric-down fa-fw fas"></i> fas fa-sort-numeric-down</li>
            <li><i className="fa-sort-numeric-up fa-fw fas"></i> fas fa-sort-numeric-up</li>
            <li><i className="fa-sort-up fa-fw fas"></i> fas fa-sort-up</li>
            <li><i className="fa-space-shuttle fa-fw fas"></i> fas fa-space-shuttle</li>
            <li><i className="fa-spinner fa-fw fas"></i> fas fa-spinner</li>
            <li><i className="fa-square fa-fw fas"></i> fas fa-square</li>
            <li><i className="fa-square-full fa-fw fas"></i> fas fa-square-full</li>
            <li><i className="fa-star fa-fw fas"></i> fas fa-star</li>
            <li><i className="fa-star-half fa-fw fas"></i> fas fa-star-half</li>
            <li><i className="fa-step-backward fa-fw fas"></i> fas fa-step-backward</li>
            <li><i className="fa-step-forward fa-fw fas"></i> fas fa-step-forward</li>
            <li><i className="fa-stethoscope fa-fw fas"></i> fas fa-stethoscope</li>
            <li><i className="fa-sticky-note fa-fw fas"></i> fas fa-sticky-note</li>
            <li><i className="fa-stop fa-fw fas"></i> fas fa-stop</li>
            <li><i className="fa-stop-circle fa-fw fas"></i> fas fa-stop-circle</li>
            <li><i className="fa-stopwatch fa-fw fas"></i> fas fa-stopwatch</li>
            <li><i className="fa-street-view fa-fw fas"></i> fas fa-street-view</li>
            <li><i className="fa-strikethrough fa-fw fas"></i> fas fa-strikethrough</li>
            <li><i className="fa-subscript fa-fw fas"></i> fas fa-subscript</li>
            <li><i className="fa-subway fa-fw fas"></i> fas fa-subway</li>
            <li><i className="fa-suitcase fa-fw fas"></i> fas fa-suitcase</li>
            <li><i className="fa-sun fa-fw fas"></i> fas fa-sun</li>
            <li><i className="fa-superscript fa-fw fas"></i> fas fa-superscript</li>
            <li><i className="fa-sync fa-fw fas"></i> fas fa-sync</li>
            <li><i className="fa-sync-alt fa-fw fas"></i> fas fa-sync-alt</li>
            <li><i className="fa-syringe fa-fw fas"></i> fas fa-syringe</li>
            <li><i className="fa-table fa-fw fas"></i> fas fa-table</li>
            <li><i className="fa-table-tennis fa-fw fas"></i> fas fa-table-tennis</li>
            <li><i className="fa-tablet fa-fw fas"></i> fas fa-tablet</li>
            <li><i className="fa-tablet-alt fa-fw fas"></i> fas fa-tablet-alt</li>
            <li><i className="fa-tablets fa-fw fas"></i> fas fa-tablets</li>
            <li><i className="fa-tachometer-alt fa-fw fas"></i> fas fa-tachometer-alt</li>
            <li><i className="fa-tag fa-fw fas"></i> fas fa-tag</li>
            <li><i className="fa-tags fa-fw fas"></i> fas fa-tags</li>
            <li><i className="fa-tape fa-fw fas"></i> fas fa-tape</li>
            <li><i className="fa-tasks fa-fw fas"></i> fas fa-tasks</li>
            <li><i className="fa-taxi fa-fw fas"></i> fas fa-taxi</li>
            <li><i className="fa-terminal fa-fw fas"></i> fas fa-terminal</li>
            <li><i className="fa-text-height fa-fw fas"></i> fas fa-text-height</li>
            <li><i className="fa-text-width fa-fw fas"></i> fas fa-text-width</li>
            <li><i className="fa-th fa-fw fas"></i> fas fa-th</li>
            <li><i className="fa-th-large fa-fw fas"></i> fas fa-th-large</li>
            <li><i className="fa-th-list fa-fw fas"></i> fas fa-th-list</li>
            <li><i className="fa-thermometer fa-fw fas"></i> fas fa-thermometer</li>
            <li><i className="fa-thermometer-empty fa-fw fas"></i> fas fa-thermometer-empty</li>
            <li><i className="fa-thermometer-full fa-fw fas"></i> fas fa-thermometer-full</li>
            <li><i className="fa-thermometer-half fa-fw fas"></i> fas fa-thermometer-half</li>
            <li><i className="fa-thermometer-quarter fa-fw fas"></i> fas fa-thermometer-quarter</li>
            <li><i className="fa-thermometer-three-quarters fa-fw fas"></i> fas fa-thermometer-three-quarters</li>
            <li><i className="fa-thumbs-down fa-fw fas"></i> fas fa-thumbs-down</li>
            <li><i className="fa-thumbs-up fa-fw fas"></i> fas fa-thumbs-up</li>
            <li><i className="fa-thumbtack fa-fw fas"></i> fas fa-thumbtack</li>
            <li><i className="fa-ticket-alt fa-fw fas"></i> fas fa-ticket-alt</li>
            <li><i className="fa-times fa-fw fas"></i> fas fa-times</li>
            <li><i className="fa-times-circle fa-fw fas"></i> fas fa-times-circle</li>
            <li><i className="fa-tint fa-fw fas"></i> fas fa-tint</li>
            <li><i className="fa-toggle-off fa-fw fas"></i> fas fa-toggle-off</li>
            <li><i className="fa-toggle-on fa-fw fas"></i> fas fa-toggle-on</li>
            <li><i className="fa-trademark fa-fw fas"></i> fas fa-trademark</li>
            <li><i className="fa-train fa-fw fas"></i> fas fa-train</li>
            <li><i className="fa-transgender fa-fw fas"></i> fas fa-transgender</li>
            <li><i className="fa-transgender-alt fa-fw fas"></i> fas fa-transgender-alt</li>
            <li><i className="fa-trash fa-fw fas"></i> fas fa-trash</li>
            <li><i className="fa-trash-alt fa-fw fas"></i> fas fa-trash-alt</li>
            <li><i className="fa-tree fa-fw fas"></i> fas fa-tree</li>
            <li><i className="fa-trophy fa-fw fas"></i> fas fa-trophy</li>
            <li><i className="fa-truck fa-fw fas"></i> fas fa-truck</li>
            <li><i className="fa-truck-loading fa-fw fas"></i> fas fa-truck-loading</li>
            <li><i className="fa-truck-moving fa-fw fas"></i> fas fa-truck-moving</li>
            <li><i className="fa-tty fa-fw fas"></i> fas fa-tty</li>
            <li><i className="fa-tv fa-fw fas"></i> fas fa-tv</li>
            <li><i className="fa-umbrella fa-fw fas"></i> fas fa-umbrella</li>
            <li><i className="fa-underline fa-fw fas"></i> fas fa-underline</li>
            <li><i className="fa-undo fa-fw fas"></i> fas fa-undo</li>
            <li><i className="fa-undo-alt fa-fw fas"></i> fas fa-undo-alt</li>
            <li><i className="fa-universal-access fa-fw fas"></i> fas fa-universal-access</li>
            <li><i className="fa-university fa-fw fas"></i> fas fa-university</li>
            <li><i className="fa-unlink fa-fw fas"></i> fas fa-unlink</li>
            <li><i className="fa-unlock fa-fw fas"></i> fas fa-unlock</li>
            <li><i className="fa-unlock-alt fa-fw fas"></i> fas fa-unlock-alt</li>
            <li><i className="fa-upload fa-fw fas"></i> fas fa-upload</li>
            <li><i className="fa-user fa-fw fas"></i> fas fa-user</li>
            <li><i className="fa-user-circle fa-fw fas"></i> fas fa-user-circle</li>
            <li><i className="fa-user-md fa-fw fas"></i> fas fa-user-md</li>
            <li><i className="fa-user-plus fa-fw fas"></i> fas fa-user-plus</li>
            <li><i className="fa-user-secret fa-fw fas"></i> fas fa-user-secret</li>
            <li><i className="fa-user-times fa-fw fas"></i> fas fa-user-times</li>
            <li><i className="fa-users fa-fw fas"></i> fas fa-users</li>
            <li><i className="fa-utensil-spoon fa-fw fas"></i> fas fa-utensil-spoon</li>
            <li><i className="fa-utensils fa-fw fas"></i> fas fa-utensils</li>
            <li><i className="fa-venus fa-fw fas"></i> fas fa-venus</li>
            <li><i className="fa-venus-double fa-fw fas"></i> fas fa-venus-double</li>
            <li><i className="fa-venus-mars fa-fw fas"></i> fas fa-venus-mars</li>
            <li><i className="fa-vial fa-fw fas"></i> fas fa-vial</li>
            <li><i className="fa-vials fa-fw fas"></i> fas fa-vials</li>
            <li><i className="fa-video fa-fw fas"></i> fas fa-video</li>
            <li><i className="fa-video-slash fa-fw fas"></i> fas fa-video-slash</li>
            <li><i className="fa-volleyball-ball fa-fw fas"></i> fas fa-volleyball-ball</li>
            <li><i className="fa-volume-down fa-fw fas"></i> fas fa-volume-down</li>
            <li><i className="fa-volume-off fa-fw fas"></i> fas fa-volume-off</li>
            <li><i className="fa-volume-up fa-fw fas"></i> fas fa-volume-up</li>
            <li><i className="fa-warehouse fa-fw fas"></i> fas fa-warehouse</li>
            <li><i className="fa-weight fa-fw fas"></i> fas fa-weight</li>
            <li><i className="fa-wheelchair fa-fw fas"></i> fas fa-wheelchair</li>
            <li><i className="fa-wifi fa-fw fas"></i> fas fa-wifi</li>
            <li><i className="fa-window-close fa-fw fas"></i> fas fa-window-close</li>
            <li><i className="fa-window-maximize fa-fw fas"></i> fas fa-window-maximize</li>
            <li><i className="fa-window-minimize fa-fw fas"></i> fas fa-window-minimize</li>
            <li><i className="fa-window-restore fa-fw fas"></i> fas fa-window-restore</li>
            <li><i className="fa-wine-glass fa-fw fas"></i> fas fa-wine-glass</li>
            <li><i className="fa-won-sign fa-fw fas"></i> fas fa-won-sign</li>
            <li><i className="fa-wrench fa-fw fas"></i> fas fa-wrench</li>
            <li><i className="fa-x-ray fa-fw fas"></i> fas fa-x-ray</li>
            <li><i className="fa-yen-sign fa-fw fas"></i> fas fa-yen-sign</li>
          </ul>
        </div>
      </div>
      <div className="clear btmspace-50">
        <h2>Regular Icons (far)</h2>
        <div className="one_quarter first">
          <ul className="nospace">
            <li><i className="fa-address-book fa-fw far"></i> far fa-address-book</li>
            <li><i className="fa-address-card fa-fw far"></i> far fa-address-card</li>
            <li><i className="fa-arrow-alt-circle-down fa-fw far"></i> far fa-arrow-alt-circle-down</li>
            <li><i className="fa-arrow-alt-circle-left fa-fw far"></i> far fa-arrow-alt-circle-left</li>
            <li><i className="fa-arrow-alt-circle-right fa-fw far"></i> far fa-arrow-alt-circle-right</li>
            <li><i className="fa-arrow-alt-circle-up fa-fw far"></i> far fa-arrow-alt-circle-up</li>
            <li><i className="fa-bell fa-fw far"></i> far fa-bell</li>
            <li><i className="fa-bell-slash fa-fw far"></i> far fa-bell-slash</li>
            <li><i className="fa-bookmark fa-fw far"></i> far fa-bookmark</li>
            <li><i className="fa-building fa-fw far"></i> far fa-building</li>
            <li><i className="fa-calendar fa-fw far"></i> far fa-calendar</li>
            <li><i className="fa-calendar-alt fa-fw far"></i> far fa-calendar-alt</li>
            <li><i className="fa-calendar-check fa-fw far"></i> far fa-calendar-check</li>
            <li><i className="fa-calendar-minus fa-fw far"></i> far fa-calendar-minus</li>
            <li><i className="fa-calendar-plus fa-fw far"></i> far fa-calendar-plus</li>
            <li><i className="fa-calendar-times fa-fw far"></i> far fa-calendar-times</li>
            <li><i className="fa-caret-square-down fa-fw far"></i> far fa-caret-square-down</li>
            <li><i className="fa-caret-square-left fa-fw far"></i> far fa-caret-square-left</li>
            <li><i className="fa-caret-square-right fa-fw far"></i> far fa-caret-square-right</li>
            <li><i className="fa-caret-square-up fa-fw far"></i> far fa-caret-square-up</li>
            <li><i className="fa-chart-bar fa-fw far"></i> far fa-chart-bar</li>
            <li><i className="fa-check-circle fa-fw far"></i> far fa-check-circle</li>
            <li><i className="fa-check-square fa-fw far"></i> far fa-check-square</li>
            <li><i className="fa-circle fa-fw far"></i> far fa-circle</li>
            <li><i className="fa-clipboard fa-fw far"></i> far fa-clipboard</li>
            <li><i className="fa-clock fa-fw far"></i> far fa-clock</li>
            <li><i className="fa-clone fa-fw far"></i> far fa-clone</li>
            <li><i className="fa-closed-captioning fa-fw far"></i> far fa-closed-captioning</li>
            <li><i className="fa-comment fa-fw far"></i> far fa-comment</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-comment-alt fa-fw far"></i> far fa-comment-alt</li>
            <li><i className="fa-comments fa-fw far"></i> far fa-comments</li>
            <li><i className="fa-compass fa-fw far"></i> far fa-compass</li>
            <li><i className="fa-copy fa-fw far"></i> far fa-copy</li>
            <li><i className="fa-copyright fa-fw far"></i> far fa-copyright</li>
            <li><i className="fa-credit-card fa-fw far"></i> far fa-credit-card</li>
            <li><i className="fa-dot-circle fa-fw far"></i> far fa-dot-circle</li>
            <li><i className="fa-edit fa-fw far"></i> far fa-edit</li>
            <li><i className="fa-envelope fa-fw far"></i> far fa-envelope</li>
            <li><i className="fa-envelope-open fa-fw far"></i> far fa-envelope-open</li>
            <li><i className="fa-eye-slash fa-fw far"></i> far fa-eye-slash</li>
            <li><i className="fa-file fa-fw far"></i> far fa-file</li>
            <li><i className="fa-file-alt fa-fw far"></i> far fa-file-alt</li>
            <li><i className="fa-file-archive fa-fw far"></i> far fa-file-archive</li>
            <li><i className="fa-file-audio fa-fw far"></i> far fa-file-audio</li>
            <li><i className="fa-file-code fa-fw far"></i> far fa-file-code</li>
            <li><i className="fa-file-excel fa-fw far"></i> far fa-file-excel</li>
            <li><i className="fa-file-image fa-fw far"></i> far fa-file-image</li>
            <li><i className="fa-file-pdf fa-fw far"></i> far fa-file-pdf</li>
            <li><i className="fa-file-powerpoint fa-fw far"></i> far fa-file-powerpoint</li>
            <li><i className="fa-file-video fa-fw far"></i> far fa-file-video</li>
            <li><i className="fa-file-word fa-fw far"></i> far fa-file-word</li>
            <li><i className="fa-flag fa-fw far"></i> far fa-flag</li>
            <li><i className="fa-folder fa-fw far"></i> far fa-folder</li>
            <li><i className="fa-folder-open fa-fw far"></i> far fa-folder-open</li>
            <li><i className="fa-frown fa-fw far"></i> far fa-frown</li>
            <li><i className="fa-futbol fa-fw far"></i> far fa-futbol</li>
            <li><i className="fa-gem fa-fw far"></i> far fa-gem</li>
            <li><i className="fa-hand-lizard fa-fw far"></i> far fa-hand-lizard</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-hand-paper fa-fw far"></i> far fa-hand-paper</li>
            <li><i className="fa-hand-peace fa-fw far"></i> far fa-hand-peace</li>
            <li><i className="fa-hand-point-down fa-fw far"></i> far fa-hand-point-down</li>
            <li><i className="fa-hand-point-left fa-fw far"></i> far fa-hand-point-left</li>
            <li><i className="fa-hand-point-right fa-fw far"></i> far fa-hand-point-right</li>
            <li><i className="fa-hand-point-up fa-fw far"></i> far fa-hand-point-up</li>
            <li><i className="fa-hand-pointer fa-fw far"></i> far fa-hand-pointer</li>
            <li><i className="fa-hand-rock fa-fw far"></i> far fa-hand-rock</li>
            <li><i className="fa-hand-scissors fa-fw far"></i> far fa-hand-scissors</li>
            <li><i className="fa-hand-spock fa-fw far"></i> far fa-hand-spock</li>
            <li><i className="fa-handshake fa-fw far"></i> far fa-handshake</li>
            <li><i className="fa-hdd fa-fw far"></i> far fa-hdd</li>
            <li><i className="fa-heart fa-fw far"></i> far fa-heart</li>
            <li><i className="fa-hospital fa-fw far"></i> far fa-hospital</li>
            <li><i className="fa-hourglass fa-fw far"></i> far fa-hourglass</li>
            <li><i className="fa-id-badge fa-fw far"></i> far fa-id-badge</li>
            <li><i className="fa-id-card fa-fw far"></i> far fa-id-card</li>
            <li><i className="fa-image fa-fw far"></i> far fa-image</li>
            <li><i className="fa-images fa-fw far"></i> far fa-images</li>
            <li><i className="fa-keyboard fa-fw far"></i> far fa-keyboard</li>
            <li><i className="fa-lemon fa-fw far"></i> far fa-lemon</li>
            <li><i className="fa-life-ring fa-fw far"></i> far fa-life-ring</li>
            <li><i className="fa-lightbulb fa-fw far"></i> far fa-lightbulb</li>
            <li><i className="fa-list-alt fa-fw far"></i> far fa-list-alt</li>
            <li><i className="fa-map fa-fw far"></i> far fa-map</li>
            <li><i className="fa-meh fa-fw far"></i> far fa-meh</li>
            <li><i className="fa-minus-square fa-fw far"></i> far fa-minus-square</li>
            <li><i className="fa-money-bill-alt fa-fw far"></i> far fa-money-bill-alt</li>
            <li><i className="fa-moon fa-fw far"></i> far fa-moon</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-newspaper fa-fw far"></i> far fa-newspaper</li>
            <li><i className="fa-object-group fa-fw far"></i> far fa-object-group</li>
            <li><i className="fa-object-ungroup fa-fw far"></i> far fa-object-ungroup</li>
            <li><i className="fa-paper-plane fa-fw far"></i> far fa-paper-plane</li>
            <li><i className="fa-pause-circle fa-fw far"></i> far fa-pause-circle</li>
            <li><i className="fa-play-circle fa-fw far"></i> far fa-play-circle</li>
            <li><i className="fa-plus-square fa-fw far"></i> far fa-plus-square</li>
            <li><i className="fa-question-circle fa-fw far"></i> far fa-question-circle</li>
            <li><i className="fa-registered fa-fw far"></i> far fa-registered</li>
            <li><i className="fa-save fa-fw far"></i> far fa-save</li>
            <li><i className="fa-share-square fa-fw far"></i> far fa-share-square</li>
            <li><i className="fa-smile fa-fw far"></i> far fa-smile</li>
            <li><i className="fa-snowflake fa-fw far"></i> far fa-snowflake</li>
            <li><i className="fa-square fa-fw far"></i> far fa-square</li>
            <li><i className="fa-star fa-fw far"></i> far fa-star</li>
            <li><i className="fa-star-half fa-fw far"></i> far fa-star-half</li>
            <li><i className="fa-sticky-note fa-fw far"></i> far fa-sticky-note</li>
            <li><i className="fa-stop-circle fa-fw far"></i> far fa-stop-circle</li>
            <li><i className="fa-sun fa-fw far"></i> far fa-sun</li>
            <li><i className="fa-thumbs-down fa-fw far"></i> far fa-thumbs-down</li>
            <li><i className="fa-thumbs-up fa-fw far"></i> far fa-thumbs-up</li>
            <li><i className="fa-times-circle fa-fw far"></i> far fa-times-circle</li>
            <li><i className="fa-trash-alt fa-fw far"></i> far fa-trash-alt</li>
            <li><i className="fa-user fa-fw far"></i> far fa-user</li>
            <li><i className="fa-user-circle fa-fw far"></i> far fa-user-circle</li>
            <li><i className="fa-window-close fa-fw far"></i> far fa-window-close</li>
            <li><i className="fa-window-maximize fa-fw far"></i> far fa-window-maximize</li>
            <li><i className="fa-window-minimize fa-fw far"></i> far fa-window-minimize</li>
            <li><i className="fa-window-restore fa-fw far"></i> far fa-window-restore</li>
          </ul>
        </div>
      </div>
      <div className="clear">
        <h2>Brand Icons (fab)</h2>
        <div className="one_quarter first">
          <ul className="nospace">
            <li><i className="fa-500px fa-fw fab"></i> fab fa-500px</li>
            <li><i className="fa-accessible-icon fa-fw fab"></i> fab fa-accessible-icon</li>
            <li><i className="fa-accusoft fa-fw fab"></i> fab fa-accusoft</li>
            <li><i className="fa-adn fa-fw fab"></i> fab fa-adn</li>
            <li><i className="fa-adversal fa-fw fab"></i> fab fa-adversal</li>
            <li><i className="fa-affiliatetheme fa-fw fab"></i> fab fa-affiliatetheme</li>
            <li><i className="fa-algolia fa-fw fab"></i> fab fa-algolia</li>
            <li><i className="fa-amazon fa-fw fab"></i> fab fa-amazon</li>
            <li><i className="fa-amazon-pay fa-fw fab"></i> fab fa-amazon-pay</li>
            <li><i className="fa-amilia fa-fw fab"></i> fab fa-amilia</li>
            <li><i className="fa-android fa-fw fab"></i> fab fa-android</li>
            <li><i className="fa-angellist fa-fw fab"></i> fab fa-angellist</li>
            <li><i className="fa-angrycreative fa-fw fab"></i> fab fa-angrycreative</li>
            <li><i className="fa-angular fa-fw fab"></i> fab fa-angular</li>
            <li><i className="fa-app-store fa-fw fab"></i> fab fa-app-store</li>
            <li><i className="fa-app-store-ios fa-fw fab"></i> fab fa-app-store-ios</li>
            <li><i className="fa-apper fa-fw fab"></i> fab fa-apper</li>
            <li><i className="fa-apple fa-fw fab"></i> fab fa-apple</li>
            <li><i className="fa-apple-pay fa-fw fab"></i> fab fa-apple-pay</li>
            <li><i className="fa-asymmetrik fa-fw fab"></i> fab fa-asymmetrik</li>
            <li><i className="fa-audible fa-fw fab"></i> fab fa-audible</li>
            <li><i className="fa-autoprefixer fa-fw fab"></i> fab fa-autoprefixer</li>
            <li><i className="fa-avianex fa-fw fab"></i> fab fa-avianex</li>
            <li><i className="fa-aviato fa-fw fab"></i> fab fa-aviato</li>
            <li><i className="fa-aws fa-fw fab"></i> fab fa-aws</li>
            <li><i className="fa-bandcamp fa-fw fab"></i> fab fa-bandcamp</li>
            <li><i className="fa-behance fa-fw fab"></i> fab fa-behance</li>
            <li><i className="fa-behance-square fa-fw fab"></i> fab fa-behance-square</li>
            <li><i className="fa-bimobject fa-fw fab"></i> fab fa-bimobject</li>
            <li><i className="fa-bitbucket fa-fw fab"></i> fab fa-bitbucket</li>
            <li><i className="fa-bitcoin fa-fw fab"></i> fab fa-bitcoin</li>
            <li><i className="fa-bity fa-fw fab"></i> fab fa-bity</li>
            <li><i className="fa-black-tie fa-fw fab"></i> fab fa-black-tie</li>
            <li><i className="fa-blackberry fa-fw fab"></i> fab fa-blackberry</li>
            <li><i className="fa-blogger fa-fw fab"></i> fab fa-blogger</li>
            <li><i className="fa-blogger-b fa-fw fab"></i> fab fa-blogger-b</li>
            <li><i className="fa-bluetooth fa-fw fab"></i> fab fa-bluetooth</li>
            <li><i className="fa-bluetooth-b fa-fw fab"></i> fab fa-bluetooth-b</li>
            <li><i className="fa-btc fa-fw fab"></i> fab fa-btc</li>
            <li><i className="fa-buromobelexperte fa-fw fab"></i> fab fa-buromobelexperte</li>
            <li><i className="fa-buysellads fa-fw fab"></i> fab fa-buysellads</li>
            <li><i className="fa-cc-amazon-pay fa-fw fab"></i> fab fa-cc-amazon-pay</li>
            <li><i className="fa-cc-amex fa-fw fab"></i> fab fa-cc-amex</li>
            <li><i className="fa-cc-apple-pay fa-fw fab"></i> fab fa-cc-apple-pay</li>
            <li><i className="fa-cc-diners-club fa-fw fab"></i> fab fa-cc-diners-club</li>
            <li><i className="fa-cc-discover fa-fw fab"></i> fab fa-cc-discover</li>
            <li><i className="fa-cc-jcb fa-fw fab"></i> fab fa-cc-jcb</li>
            <li><i className="fa-cc-mastercard fa-fw fab"></i> fab fa-cc-mastercard</li>
            <li><i className="fa-cc-paypal fa-fw fab"></i> fab fa-cc-paypal</li>
            <li><i className="fa-cc-stripe fa-fw fab"></i> fab fa-cc-stripe</li>
            <li><i className="fa-cc-visa fa-fw fab"></i> fab fa-cc-visa</li>
            <li><i className="fa-centercode fa-fw fab"></i> fab fa-centercode</li>
            <li><i className="fa-chrome fa-fw fab"></i> fab fa-chrome</li>
            <li><i className="fa-cloudscale fa-fw fab"></i> fab fa-cloudscale</li>
            <li><i className="fa-cloudsmith fa-fw fab"></i> fab fa-cloudsmith</li>
            <li><i className="fa-cloudversify fa-fw fab"></i> fab fa-cloudversify</li>
            <li><i className="fa-codepen fa-fw fab"></i> fab fa-codepen</li>
            <li><i className="fa-codiepie fa-fw fab"></i> fab fa-codiepie</li>
            <li><i className="fa-connectdevelop fa-fw fab"></i> fab fa-connectdevelop</li>
            <li><i className="fa-contao fa-fw fab"></i> fab fa-contao</li>
            <li><i className="fa-cpanel fa-fw fab"></i> fab fa-cpanel</li>
            <li><i className="fa-creative-commons fa-fw fab"></i> fab fa-creative-commons</li>
            <li><i className="fa-css3 fa-fw fab"></i> fab fa-css3</li>
            <li><i className="fa-css3-alt fa-fw fab"></i> fab fa-css3-alt</li>
            <li><i className="fa-cuttlefish fa-fw fab"></i> fab fa-cuttlefish</li>
            <li><i className="fa-d-and-d fa-fw fab"></i> fab fa-d-and-d</li>
            <li><i className="fa-dashcube fa-fw fab"></i> fab fa-dashcube</li>
            <li><i className="fa-delicious fa-fw fab"></i> fab fa-delicious</li>
            <li><i className="fa-deploydog fa-fw fab"></i> fab fa-deploydog</li>
            <li><i className="fa-deskpro fa-fw fab"></i> fab fa-deskpro</li>
            <li><i className="fa-deviantart fa-fw fab"></i> fab fa-deviantart</li>
            <li><i className="fa-digg fa-fw fab"></i> fab fa-digg</li>
            <li><i className="fa-digital-ocean fa-fw fab"></i> fab fa-digital-ocean</li>
            <li><i className="fa-discord fa-fw fab"></i> fab fa-discord</li>
            <li><i className="fa-discourse fa-fw fab"></i> fab fa-discourse</li>
            <li><i className="fa-dochub fa-fw fab"></i> fab fa-dochub</li>
            <li><i className="fa-docker fa-fw fab"></i> fab fa-docker</li>
            <li><i className="fa-draft2digital fa-fw fab"></i> fab fa-draft2digital</li>
            <li><i className="fa-dribbble fa-fw fab"></i> fab fa-dribbble</li>
            <li><i className="fa-dribbble-square fa-fw fab"></i> fab fa-dribbble-square</li>
            <li><i className="fa-dropbox fa-fw fab"></i> fab fa-dropbox</li>
            <li><i className="fa-drupal fa-fw fab"></i> fab fa-drupal</li>
            <li><i className="fa-dyalog fa-fw fab"></i> fab fa-dyalog</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-earlybirds fa-fw fab"></i> fab fa-earlybirds</li>
            <li><i className="fa-edge fa-fw fab"></i> fab fa-edge</li>
            <li><i className="fa-elementor fa-fw fab"></i> fab fa-elementor</li>
            <li><i className="fa-ember fa-fw fab"></i> fab fa-ember</li>
            <li><i className="fa-empire fa-fw fab"></i> fab fa-empire</li>
            <li><i className="fa-envira fa-fw fab"></i> fab fa-envira</li>
            <li><i className="fa-erlang fa-fw fab"></i> fab fa-erlang</li>
            <li><i className="fa-ethereum fa-fw fab"></i> fab fa-ethereum</li>
            <li><i className="fa-etsy fa-fw fab"></i> fab fa-etsy</li>
            <li><i className="fa-expeditedssl fa-fw fab"></i> fab fa-expeditedssl</li>
            <li><i className="fa-facebook fa-fw fab"></i> fab fa-facebook</li>
            <li><i className="fa-facebook-f fa-fw fab"></i> fab fa-facebook-f</li>
            <li><i className="fa-facebook-messenger fa-fw fab"></i> fab fa-facebook-messenger</li>
            <li><i className="fa-facebook-square fa-fw fab"></i> fab fa-facebook-square</li>
            <li><i className="fa-firefox fa-fw fab"></i> fab fa-firefox</li>
            <li><i className="fa-first-order fa-fw fab"></i> fab fa-first-order</li>
            <li><i className="fa-firstdraft fa-fw fab"></i> fab fa-firstdraft</li>
            <li><i className="fa-flickr fa-fw fab"></i> fab fa-flickr</li>
            <li><i className="fa-flipboard fa-fw fab"></i> fab fa-flipboard</li>
            <li><i className="fa-fly fa-fw fab"></i> fab fa-fly</li>
            <li><i className="fa-font-awesome fa-fw fab"></i> fab fa-font-awesome</li>
            <li><i className="fa-font-awesome-alt fa-fw fab"></i> fab fa-font-awesome-alt</li>
            <li><i className="fa-font-awesome-flag fa-fw fab"></i> fab fa-font-awesome-flag</li>
            <li><i className="fa-fonticons fa-fw fab"></i> fab fa-fonticons</li>
            <li><i className="fa-fonticons-fi fa-fw fab"></i> fab fa-fonticons-fi</li>
            <li><i className="fa-fort-awesome fa-fw fab"></i> fab fa-fort-awesome</li>
            <li><i className="fa-fort-awesome-alt fa-fw fab"></i> fab fa-fort-awesome-alt</li>
            <li><i className="fa-forumbee fa-fw fab"></i> fab fa-forumbee</li>
            <li><i className="fa-foursquare fa-fw fab"></i> fab fa-foursquare</li>
            <li><i className="fa-free-code-camp fa-fw fab"></i> fab fa-free-code-camp</li>
            <li><i className="fa-freebsd fa-fw fab"></i> fab fa-freebsd</li>
            <li><i className="fa-get-pocket fa-fw fab"></i> fab fa-get-pocket</li>
            <li><i className="fa-gg fa-fw fab"></i> fab fa-gg</li>
            <li><i className="fa-gg-circle fa-fw fab"></i> fab fa-gg-circle</li>
            <li><i className="fa-git fa-fw fab"></i> fab fa-git</li>
            <li><i className="fa-git-square fa-fw fab"></i> fab fa-git-square</li>
            <li><i className="fa-github fa-fw fab"></i> fab fa-github</li>
            <li><i className="fa-github-alt fa-fw fab"></i> fab fa-github-alt</li>
            <li><i className="fa-github-square fa-fw fab"></i> fab fa-github-square</li>
            <li><i className="fa-gitkraken fa-fw fab"></i> fab fa-gitkraken</li>
            <li><i className="fa-gitlab fa-fw fab"></i> fab fa-gitlab</li>
            <li><i className="fa-gitter fa-fw fab"></i> fab fa-gitter</li>
            <li><i className="fa-glide fa-fw fab"></i> fab fa-glide</li>
            <li><i className="fa-glide-g fa-fw fab"></i> fab fa-glide-g</li>
            <li><i className="fa-gofore fa-fw fab"></i> fab fa-gofore</li>
            <li><i className="fa-goodreads fa-fw fab"></i> fab fa-goodreads</li>
            <li><i className="fa-goodreads-g fa-fw fab"></i> fab fa-goodreads-g</li>
            <li><i className="fa-google fa-fw fab"></i> fab fa-google</li>
            <li><i className="fa-google-drive fa-fw fab"></i> fab fa-google-drive</li>
            <li><i className="fa-google-play fa-fw fab"></i> fab fa-google-play</li>
            <li><i className="fa-google-plus fa-fw fab"></i> fab fa-google-plus</li>
            <li><i className="fa-google-plus-g fa-fw fab"></i> fab fa-google-plus-g</li>
            <li><i className="fa-google-plus-square fa-fw fab"></i> fab fa-google-plus-square</li>
            <li><i className="fa-google-wallet fa-fw fab"></i> fab fa-google-wallet</li>
            <li><i className="fa-gratipay fa-fw fab"></i> fab fa-gratipay</li>
            <li><i className="fa-grav fa-fw fab"></i> fab fa-grav</li>
            <li><i className="fa-gripfire fa-fw fab"></i> fab fa-gripfire</li>
            <li><i className="fa-grunt fa-fw fab"></i> fab fa-grunt</li>
            <li><i className="fa-gulp fa-fw fab"></i> fab fa-gulp</li>
            <li><i className="fa-hacker-news fa-fw fab"></i> fab fa-hacker-news</li>
            <li><i className="fa-hacker-news-square fa-fw fab"></i> fab fa-hacker-news-square</li>
            <li><i className="fa-hips fa-fw fab"></i> fab fa-hips</li>
            <li><i className="fa-hire-a-helper fa-fw fab"></i> fab fa-hire-a-helper</li>
            <li><i className="fa-hooli fa-fw fab"></i> fab fa-hooli</li>
            <li><i className="fa-hotjar fa-fw fab"></i> fab fa-hotjar</li>
            <li><i className="fa-houzz fa-fw fab"></i> fab fa-houzz</li>
            <li><i className="fa-html5 fa-fw fab"></i> fab fa-html5</li>
            <li><i className="fa-hubspot fa-fw fab"></i> fab fa-hubspot</li>
            <li><i className="fa-imdb fa-fw fab"></i> fab fa-imdb</li>
            <li><i className="fa-instagram fa-fw fab"></i> fab fa-instagram</li>
            <li><i className="fa-internet-explorer fa-fw fab"></i> fab fa-internet-explorer</li>
            <li><i className="fa-ioxhost fa-fw fab"></i> fab fa-ioxhost</li>
            <li><i className="fa-itunes fa-fw fab"></i> fab fa-itunes</li>
            <li><i className="fa-itunes-note fa-fw fab"></i> fab fa-itunes-note</li>
            <li><i className="fa-jenkins fa-fw fab"></i> fab fa-jenkins</li>
            <li><i className="fa-joget fa-fw fab"></i> fab fa-joget</li>
            <li><i className="fa-joomla fa-fw fab"></i> fab fa-joomla</li>
            <li><i className="fa-js fa-fw fab"></i> fab fa-js</li>
            <li><i className="fa-js-square fa-fw fab"></i> fab fa-js-square</li>
            <li><i className="fa-jsfiddle fa-fw fab"></i> fab fa-jsfiddle</li>
            <li><i className="fa-keycdn fa-fw fab"></i> fab fa-keycdn</li>
            <li><i className="fa-kickstarter fa-fw fab"></i> fab fa-kickstarter</li>
            <li><i className="fa-kickstarter-k fa-fw fab"></i> fab fa-kickstarter-k</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-korvue fa-fw fab"></i> fab fa-korvue</li>
            <li><i className="fa-laravel fa-fw fab"></i> fab fa-laravel</li>
            <li><i className="fa-lastfm fa-fw fab"></i> fab fa-lastfm</li>
            <li><i className="fa-lastfm-square fa-fw fab"></i> fab fa-lastfm-square</li>
            <li><i className="fa-leanpub fa-fw fab"></i> fab fa-leanpub</li>
            <li><i className="fa-less fa-fw fab"></i> fab fa-less</li>
            <li><i className="fa-line fa-fw fab"></i> fab fa-line</li>
            <li><i className="fa-linkedin fa-fw fab"></i> fab fa-linkedin</li>
            <li><i className="fa-linkedin-in fa-fw fab"></i> fab fa-linkedin-in</li>
            <li><i className="fa-linode fa-fw fab"></i> fab fa-linode</li>
            <li><i className="fa-linux fa-fw fab"></i> fab fa-linux</li>
            <li><i className="fa-lyft fa-fw fab"></i> fab fa-lyft</li>
            <li><i className="fa-magento fa-fw fab"></i> fab fa-magento</li>
            <li><i className="fa-maxcdn fa-fw fab"></i> fab fa-maxcdn</li>
            <li><i className="fa-medapps fa-fw fab"></i> fab fa-medapps</li>
            <li><i className="fa-medium fa-fw fab"></i> fab fa-medium</li>
            <li><i className="fa-medium-m fa-fw fab"></i> fab fa-medium-m</li>
            <li><i className="fa-medrt fa-fw fab"></i> fab fa-medrt</li>
            <li><i className="fa-meetup fa-fw fab"></i> fab fa-meetup</li>
            <li><i className="fa-microsoft fa-fw fab"></i> fab fa-microsoft</li>
            <li><i className="fa-mix fa-fw fab"></i> fab fa-mix</li>
            <li><i className="fa-mixcloud fa-fw fab"></i> fab fa-mixcloud</li>
            <li><i className="fa-mizuni fa-fw fab"></i> fab fa-mizuni</li>
            <li><i className="fa-modx fa-fw fab"></i> fab fa-modx</li>
            <li><i className="fa-monero fa-fw fab"></i> fab fa-monero</li>
            <li><i className="fa-napster fa-fw fab"></i> fab fa-napster</li>
            <li><i className="fa-nintendo-switch fa-fw fab"></i> fab fa-nintendo-switch</li>
            <li><i className="fa-node fa-fw fab"></i> fab fa-node</li>
            <li><i className="fa-node-js fa-fw fab"></i> fab fa-node-js</li>
            <li><i className="fa-npm fa-fw fab"></i> fab fa-npm</li>
            <li><i className="fa-ns8 fa-fw fab"></i> fab fa-ns8</li>
            <li><i className="fa-nutritionix fa-fw fab"></i> fab fa-nutritionix</li>
            <li><i className="fa-odnoklassniki fa-fw fab"></i> fab fa-odnoklassniki</li>
            <li><i className="fa-odnoklassniki-square fa-fw fab"></i> fab fa-odnoklassniki-square</li>
            <li><i className="fa-opencart fa-fw fab"></i> fab fa-opencart</li>
            <li><i className="fa-openid fa-fw fab"></i> fab fa-openid</li>
            <li><i className="fa-opera fa-fw fab"></i> fab fa-opera</li>
            <li><i className="fa-optin-monster fa-fw fab"></i> fab fa-optin-monster</li>
            <li><i className="fa-osi fa-fw fab"></i> fab fa-osi</li>
            <li><i className="fa-page4 fa-fw fab"></i> fab fa-page4</li>
            <li><i className="fa-pagelines fa-fw fab"></i> fab fa-pagelines</li>
            <li><i className="fa-palfed fa-fw fab"></i> fab fa-palfed</li>
            <li><i className="fa-patreon fa-fw fab"></i> fab fa-patreon</li>
            <li><i className="fa-paypal fa-fw fab"></i> fab fa-paypal</li>
            <li><i className="fa-periscope fa-fw fab"></i> fab fa-periscope</li>
            <li><i className="fa-phabricator fa-fw fab"></i> fab fa-phabricator</li>
            <li><i className="fa-phoenix-framework fa-fw fab"></i> fab fa-phoenix-framework</li>
            <li><i className="fa-php fa-fw fab"></i> fab fa-php</li>
            <li><i className="fa-pied-piper fa-fw fab"></i> fab fa-pied-piper</li>
            <li><i className="fa-pied-piper-alt fa-fw fab"></i> fab fa-pied-piper-alt</li>
            <li><i className="fa-pied-piper-pp fa-fw fab"></i> fab fa-pied-piper-pp</li>
            <li><i className="fa-pinterest fa-fw fab"></i> fab fa-pinterest</li>
            <li><i className="fa-pinterest-p fa-fw fab"></i> fab fa-pinterest-p</li>
            <li><i className="fa-pinterest-square fa-fw fab"></i> fab fa-pinterest-square</li>
            <li><i className="fa-playstation fa-fw fab"></i> fab fa-playstation</li>
            <li><i className="fa-product-hunt fa-fw fab"></i> fab fa-product-hunt</li>
            <li><i className="fa-pushed fa-fw fab"></i> fab fa-pushed</li>
            <li><i className="fa-python fa-fw fab"></i> fab fa-python</li>
            <li><i className="fa-qq fa-fw fab"></i> fab fa-qq</li>
            <li><i className="fa-quinscape fa-fw fab"></i> fab fa-quinscape</li>
            <li><i className="fa-quora fa-fw fab"></i> fab fa-quora</li>
            <li><i className="fa-ravelry fa-fw fab"></i> fab fa-ravelry</li>
            <li><i className="fa-react fa-fw fab"></i> fab fa-react</li>
            <li><i className="fa-readme fa-fw fab"></i> fab fa-readme</li>
            <li><i className="fa-rebel fa-fw fab"></i> fab fa-rebel</li>
            <li><i className="fa-red-river fa-fw fab"></i> fab fa-red-river</li>
            <li><i className="fa-reddit fa-fw fab"></i> fab fa-reddit</li>
            <li><i className="fa-reddit-alien fa-fw fab"></i> fab fa-reddit-alien</li>
            <li><i className="fa-reddit-square fa-fw fab"></i> fab fa-reddit-square</li>
            <li><i className="fa-rendact fa-fw fab"></i> fab fa-rendact</li>
            <li><i className="fa-renren fa-fw fab"></i> fab fa-renren</li>
            <li><i className="fa-replyd fa-fw fab"></i> fab fa-replyd</li>
            <li><i className="fa-resolving fa-fw fab"></i> fab fa-resolving</li>
            <li><i className="fa-rocketchat fa-fw fab"></i> fab fa-rocketchat</li>
            <li><i className="fa-rockrms fa-fw fab"></i> fab fa-rockrms</li>
            <li><i className="fa-safari fa-fw fab"></i> fab fa-safari</li>
            <li><i className="fa-sass fa-fw fab"></i> fab fa-sass</li>
            <li><i className="fa-schlix fa-fw fab"></i> fab fa-schlix</li>
            <li><i className="fa-scribd fa-fw fab"></i> fab fa-scribd</li>
            <li><i className="fa-searchengin fa-fw fab"></i> fab fa-searchengin</li>
            <li><i className="fa-sellcast fa-fw fab"></i> fab fa-sellcast</li>
            <li><i className="fa-sellsy fa-fw fab"></i> fab fa-sellsy</li>
            <li><i className="fa-servicestack fa-fw fab"></i> fab fa-servicestack</li>
          </ul>
        </div>
        <div className="one_quarter">
          <ul className="nospace">
            <li><i className="fa-shirtsinbulk fa-fw fab"></i> fab fa-shirtsinbulk</li>
            <li><i className="fa-simplybuilt fa-fw fab"></i> fab fa-simplybuilt</li>
            <li><i className="fa-sistrix fa-fw fab"></i> fab fa-sistrix</li>
            <li><i className="fa-skyatlas fa-fw fab"></i> fab fa-skyatlas</li>
            <li><i className="fa-skype fa-fw fab"></i> fab fa-skype</li>
            <li><i className="fa-slack fa-fw fab"></i> fab fa-slack</li>
            <li><i className="fa-slack-hash fa-fw fab"></i> fab fa-slack-hash</li>
            <li><i className="fa-slideshare fa-fw fab"></i> fab fa-slideshare</li>
            <li><i className="fa-snapchat fa-fw fab"></i> fab fa-snapchat</li>
            <li><i className="fa-snapchat-ghost fa-fw fab"></i> fab fa-snapchat-ghost</li>
            <li><i className="fa-snapchat-square fa-fw fab"></i> fab fa-snapchat-square</li>
            <li><i className="fa-soundcloud fa-fw fab"></i> fab fa-soundcloud</li>
            <li><i className="fa-speakap fa-fw fab"></i> fab fa-speakap</li>
            <li><i className="fa-spotify fa-fw fab"></i> fab fa-spotify</li>
            <li><i className="fa-stack-exchange fa-fw fab"></i> fab fa-stack-exchange</li>
            <li><i className="fa-stack-overflow fa-fw fab"></i> fab fa-stack-overflow</li>
            <li><i className="fa-staylinked fa-fw fab"></i> fab fa-staylinked</li>
            <li><i className="fa-steam fa-fw fab"></i> fab fa-steam</li>
            <li><i className="fa-steam-square fa-fw fab"></i> fab fa-steam-square</li>
            <li><i className="fa-steam-symbol fa-fw fab"></i> fab fa-steam-symbol</li>
            <li><i className="fa-sticker-mule fa-fw fab"></i> fab fa-sticker-mule</li>
            <li><i className="fa-strava fa-fw fab"></i> fab fa-strava</li>
            <li><i className="fa-stripe fa-fw fab"></i> fab fa-stripe</li>
            <li><i className="fa-stripe-s fa-fw fab"></i> fab fa-stripe-s</li>
            <li><i className="fa-studiovinari fa-fw fab"></i> fab fa-studiovinari</li>
            <li><i className="fa-stumbleupon fa-fw fab"></i> fab fa-stumbleupon</li>
            <li><i className="fa-stumbleupon-circle fa-fw fab"></i> fab fa-stumbleupon-circle</li>
            <li><i className="fa-superpowers fa-fw fab"></i> fab fa-superpowers</li>
            <li><i className="fa-supple fa-fw fab"></i> fab fa-supple</li>
            <li><i className="fa-telegram fa-fw fab"></i> fab fa-telegram</li>
            <li><i className="fa-telegram-plane fa-fw fab"></i> fab fa-telegram-plane</li>
            <li><i className="fa-tencent-weibo fa-fw fab"></i> fab fa-tencent-weibo</li>
            <li><i className="fa-themeisle fa-fw fab"></i> fab fa-themeisle</li>
            <li><i className="fa-trello fa-fw fab"></i> fab fa-trello</li>
            <li><i className="fa-tripadvisor fa-fw fab"></i> fab fa-tripadvisor</li>
            <li><i className="fa-tumblr fa-fw fab"></i> fab fa-tumblr</li>
            <li><i className="fa-tumblr-square fa-fw fab"></i> fab fa-tumblr-square</li>
            <li><i className="fa-twitch fa-fw fab"></i> fab fa-twitch</li>
            <li><i className="fa-twitter fa-fw fab"></i> fab fa-twitter</li>
            <li><i className="fa-twitter-square fa-fw fab"></i> fab fa-twitter-square</li>
            <li><i className="fa-typo3 fa-fw fab"></i> fab fa-typo3</li>
            <li><i className="fa-uber fa-fw fab"></i> fab fa-uber</li>
            <li><i className="fa-uikit fa-fw fab"></i> fab fa-uikit</li>
            <li><i className="fa-uniregistry fa-fw fab"></i> fab fa-uniregistry</li>
            <li><i className="fa-untappd fa-fw fab"></i> fab fa-untappd</li>
            <li><i className="fa-usb fa-fw fab"></i> fab fa-usb</li>
            <li><i className="fa-ussunnah fa-fw fab"></i> fab fa-ussunnah</li>
            <li><i className="fa-vaadin fa-fw fab"></i> fab fa-vaadin</li>
            <li><i className="fa-viacoin fa-fw fab"></i> fab fa-viacoin</li>
            <li><i className="fa-viadeo fa-fw fab"></i> fab fa-viadeo</li>
            <li><i className="fa-viadeo-square fa-fw fab"></i> fab fa-viadeo-square</li>
            <li><i className="fa-viber fa-fw fab"></i> fab fa-viber</li>
            <li><i className="fa-vimeo fa-fw fab"></i> fab fa-vimeo</li>
            <li><i className="fa-vimeo-square fa-fw fab"></i> fab fa-vimeo-square</li>
            <li><i className="fa-vimeo-v fa-fw fab"></i> fab fa-vimeo-v</li>
            <li><i className="fa-vine fa-fw fab"></i> fab fa-vine</li>
            <li><i className="fa-vk fa-fw fab"></i> fab fa-vk</li>
            <li><i className="fa-vnv fa-fw fab"></i> fab fa-vnv</li>
            <li><i className="fa-vuejs fa-fw fab"></i> fab fa-vuejs</li>
            <li><i className="fa-weibo fa-fw fab"></i> fab fa-weibo</li>
            <li><i className="fa-weixin fa-fw fab"></i> fab fa-weixin</li>
            <li><i className="fa-whatsapp fa-fw fab"></i> fab fa-whatsapp</li>
            <li><i className="fa-whatsapp-square fa-fw fab"></i> fab fa-whatsapp-square</li>
            <li><i className="fa-whmcs fa-fw fab"></i> fab fa-whmcs</li>
            <li><i className="fa-wikipedia-w fa-fw fab"></i> fab fa-wikipedia-w</li>
            <li><i className="fa-windows fa-fw fab"></i> fab fa-windows</li>
            <li><i className="fa-wordpress fa-fw fab"></i> fab fa-wordpress</li>
            <li><i className="fa-wordpress-simple fa-fw fab"></i> fab fa-wordpress-simple</li>
            <li><i className="fa-wpbeginner fa-fw fab"></i> fab fa-wpbeginner</li>
            <li><i className="fa-wpexplorer fa-fw fab"></i> fab fa-wpexplorer</li>
            <li><i className="fa-wpforms fa-fw fab"></i> fab fa-wpforms</li>
            <li><i className="fa-xbox fa-fw fab"></i> fab fa-xbox</li>
            <li><i className="fa-xing fa-fw fab"></i> fab fa-xing</li>
            <li><i className="fa-xing-square fa-fw fab"></i> fab fa-xing-square</li>
            <li><i className="fa-y-combinator fa-fw fab"></i> fab fa-y-combinator</li>
            <li><i className="fa-yahoo fa-fw fab"></i> fab fa-yahoo</li>
            <li><i className="fa-yandex fa-fw fab"></i> fab fa-yandex</li>
            <li><i className="fa-yandex-international fa-fw fab"></i> fab fa-yandex-international</li>
            <li><i className="fa-yelp fa-fw fab"></i> fab fa-yelp</li>
            <li><i className="fa-yoast fa-fw fab"></i> fab fa-yoast</li>
            <li><i className="fa-youtube fa-fw fab"></i> fab fa-youtube</li>
            <li><i className="fa-youtube-square fa-fw fab"></i> fab fa-youtube-square</li>
          </ul>
        </div>
      </div>
      
    </div>
    
   {/*  <!-- / main body --> */}
    <div className="clear"></div>
  </main>
</div>



<Footer/>
<a id="backtotop" href="#top"><i className="fas fa-chevron-up"></i></a>
{/* <!-- JAVASCRIPTS -->
<script src="../layout/scripts/jquery.min.js"></script>
<script src="../layout/scripts/jquery.backtotop.js"></script>
<script src="../layout/scripts/jquery.mobilemenu.js"></script> */}
            
        </div>
    )
}

export default FontIcons
